LIGHTING = 'Lighting'
SWITCHABLE = 'Switchable'
THERMOSTAT = 'Thermostat'
CURRENT_TEMPERATURE = 'CurrentTemperature'
TARGET_TEMPERATURE = 'TargetTemperature'
HEATING_COOLING_MODE = 'homekit:HeatingCoolingMode'
BLINDS = 'Blinds'